#!/usr/bin/env python3
import argparse
import datetime as _datetime
import os
import re
import struct
import subprocess
import sys
import tempfile


SAMPLE_RATE = 48000
CHANNELS = 1
BITS_PER_SAMPLE = 8
BYTES_PER_SAMPLE = 1
LOWPASS_HZ = 20000
INPUT_HEADROOM = "0.75"
BPM_MIN = 100
BPM_MAX = 200
LOOP_BEAT_COUNTS = (4, 8, 16, 32, 48, 64, 72, 96)


def run_sox(input_path):
    with tempfile.TemporaryDirectory() as temp_dir:
        filtered_path = os.path.join(temp_dir, "filtered.wav")
        filter_cmd = [
            "sox",
            "-v",
            INPUT_HEADROOM,
            input_path,
            filtered_path,
            "lowpass",
            str(LOWPASS_HZ),
            "gain",
            "-n",
            "-1",
        ]
        convert_cmd = [
            "sox",
            filtered_path,
            "-r",
            str(SAMPLE_RATE),
            "-c",
            str(CHANNELS),
            "-b",
            str(BITS_PER_SAMPLE),
            "-e",
            "signed-integer",
            "-L",
            "-t",
            "raw",
            "-",
        ]
        try:
            subprocess.check_call(filter_cmd)
            return subprocess.check_output(convert_cmd)
        except FileNotFoundError:
            print("error: sox is required to encode breaky audio", file=sys.stderr)
            raise SystemExit(1)
        except subprocess.CalledProcessError as exc:
            print("error: sox failed while encoding audio", file=sys.stderr)
            raise SystemExit(exc.returncode)


def encode(raw):
    frame_size = CHANNELS * BYTES_PER_SAMPLE
    if len(raw) % frame_size != 0:
        raise ValueError("raw audio length is not an even number of mono frames")

    packed = bytearray()
    peak = 0
    frame_count = len(raw) // frame_size
    for index in range(frame_count):
        sample = struct.unpack_from("<b", raw, index * frame_size)[0]
        peak = max(peak, abs(sample))
        packed.append(sample & 0xFF)
    return packed, frame_count, peak


def infer_bpm_from_filename(input_path):
    match = re.search(r"bpm[_-]?(\d+(?:\.\d+)?)", os.path.basename(input_path), re.IGNORECASE)
    if not match:
        return None
    bpm = round(float(match.group(1)))
    if bpm <= 0:
        return None
    return bpm


def estimate_bpm_from_loop(frame_count):
    seconds = frame_count / SAMPLE_RATE
    candidates = []
    for beats in LOOP_BEAT_COUNTS:
        bpm = (beats * 60.0) / seconds
        clamped_bpm = min(max(bpm, BPM_MIN), BPM_MAX)
        range_error = abs(bpm - clamped_bpm)
        rounded_bpm = round(clamped_bpm)
        integer_error = abs(clamped_bpm - rounded_bpm)
        if BPM_MIN <= bpm <= BPM_MAX:
            candidates.append((0.0, integer_error, -beats, rounded_bpm, beats, bpm))
        else:
            candidates.append((range_error, integer_error, -beats, rounded_bpm, beats, bpm))

    if not candidates:
        raise ValueError(
            f"could not estimate BPM from {seconds:.3f}s"
        )

    _, _, _, rounded_bpm, beats, exact_bpm = min(candidates)
    return rounded_bpm, beats, exact_bpm


def resolve_bpm(input_path, frame_count, override_bpm):
    if override_bpm is not None:
        return round(override_bpm), "from --bpm"

    source_bpm = infer_bpm_from_filename(input_path)
    if source_bpm is not None:
        return source_bpm, "from filename"

    source_bpm, beats, exact_bpm = estimate_bpm_from_loop(frame_count)
    bpm_note = f"estimated from {beats} beats at exact {exact_bpm:.2f} BPM"
    if source_bpm != round(exact_bpm):
        bpm_note += f", clamped to {source_bpm}"
    return source_bpm, bpm_note


def encode_file(input_path, override_bpm=None):
    raw = run_sox(input_path)
    packed, frame_count, peak = encode(raw)
    source_bpm, bpm_note = resolve_bpm(input_path, frame_count, override_bpm)
    return {
        "path": input_path,
        "packed": packed,
        "frame_count": frame_count,
        "source_bpm": source_bpm,
        "bpm_note": bpm_note,
        "peak": peak,
    }


def write_header(output_path, samples):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    generated = _datetime.datetime.now(_datetime.timezone.utc).isoformat()
    audio_bytes = sum(len(sample["packed"]) for sample in samples)
    with open(output_path, "w", encoding="utf-8") as out:
        out.write("// Generated by scripts/encode_audio.py. Do not edit by hand.\n")
        for index, sample in enumerate(samples):
            out.write(
                f"// Source {index}: {sample['path']} "
                f"({sample['source_bpm']} BPM, {sample['bpm_note']})\n"
            )
        out.write(f"// Generated: {generated}\n")
        out.write("#pragma once\n\n")
        out.write("#include <stdint.h>\n")
        out.write("#include \"pico/platform.h\"\n\n")
        out.write(f"#define BREAKY_SAMPLE_RATE {SAMPLE_RATE}u\n")
        out.write(f"#define BREAKY_AUDIO_CHANNELS {CHANNELS}u\n")
        out.write(f"#define BREAKY_AUDIO_BITS {BITS_PER_SAMPLE}u\n")
        out.write(f"#define BREAKY_LOWPASS_HZ {LOWPASS_HZ}u\n")
        out.write(f"#define BREAKY_SAMPLE_COUNT {len(samples)}u\n")
        out.write(f"#define BREAKY_AUDIO_BYTES {audio_bytes}u\n\n")
        out.write("struct BreakyAudioSample {\n")
        out.write("    uint32_t offset;\n")
        out.write("    uint32_t frame_count;\n")
        out.write("    uint16_t source_bpm;\n")
        out.write("    uint8_t peak;\n")
        out.write("};\n\n")
        out.write(
            "static const BreakyAudioSample __in_flash(\"breaky_audio\") "
            "breaky_audio_samples[BREAKY_SAMPLE_COUNT] = {\n"
        )
        offset = 0
        for sample in samples:
            out.write(
                f"    {{{offset}u, {sample['frame_count']}u, "
                f"{sample['source_bpm']}u, {sample['peak']}u}},\n"
            )
            offset += len(sample["packed"])
        out.write("};\n\n")
        out.write(
            "static const uint8_t __in_flash(\"breaky_audio\") "
            "breaky_audio_data[BREAKY_AUDIO_BYTES] = {\n"
        )
        written = 0
        for sample in samples:
            out.write(f"    // {sample['path']}\n")
            packed = sample["packed"]
            for i in range(0, len(packed), 18):
                chunk = packed[i : i + 18]
                out.write("    ")
                out.write(", ".join(f"0x{byte:02x}" for byte in chunk))
                written += len(chunk)
                if written < audio_bytes:
                    out.write(",")
                out.write("\n")
            if len(packed) == 0 and written < audio_bytes:
                out.write(",")
        out.write("};\n")


def main():
    parser = argparse.ArgumentParser(description="Encode Breaky audio as signed 8-bit mono.")
    parser.add_argument(
        "--bpm",
        type=float,
        help=(
            "source audio BPM; defaults to inferring bpmNNN from filename, "
            f"then estimating from duration as one of {LOOP_BEAT_COUNTS} beats "
            f"between {BPM_MIN} and {BPM_MAX} BPM"
        ),
    )
    parser.add_argument("paths", nargs="+", help="input WAV file(s), followed by output header")
    args = parser.parse_args()
    if len(args.paths) < 2:
        print("error: provide at least one input WAV and one output header", file=sys.stderr)
        raise SystemExit(1)

    if args.bpm is not None and args.bpm <= 0:
        print("error: source BPM must be positive", file=sys.stderr)
        raise SystemExit(1)
    if args.bpm is not None and len(args.paths) > 2:
        print("error: --bpm can only be used with a single input file", file=sys.stderr)
        raise SystemExit(1)

    input_paths = args.paths[:-1]
    output_path = args.paths[-1]
    samples = []
    for input_path in input_paths:
        try:
            sample = encode_file(input_path, args.bpm)
        except ValueError as exc:
            print(f"error: {exc}", file=sys.stderr)
            raise SystemExit(1)
        samples.append(sample)

    write_header(output_path, samples)
    total_bytes = sum(len(sample["packed"]) for sample in samples)
    for index, sample in enumerate(samples):
        seconds = sample["frame_count"] / SAMPLE_RATE
        print(
            f"encoded sample {index}: {sample['path']}, "
            f"{sample['frame_count']} mono frames ({seconds:.2f}s), "
            f"{len(sample['packed'])} bytes, source bpm {sample['source_bpm']} "
            f"({sample['bpm_note']}), source peak {sample['peak']}/127"
        )
    print(f"encoded {len(samples)} samples, {total_bytes} total bytes")


if __name__ == "__main__":
    main()
